// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EMPDB.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeNumber { get; set; }

    public string EmployeeName { get; set; }

    public DateTime DOB { get; set; }

    public DateTime DOH { get; set; }

    public decimal GrossSalary { get; set; }

    public decimal NetSalary { get; set; }

    public int Departmentid { get; set; }

    public virtual Department Department { get; set; }
}